project:
  type: book

book:
  title: "Introduction to Machine Learning"

  chapters:
    - index.qmd

    - part: "Self-study"
      chapters:
        - notebooks/001_getting_started.ipynb
        - notebooks/002_classification.ipynb
        - notebooks/003_regression.ipynb
        - notebooks/004_unsupervised_learning.ipynb
        - notebooks/005_data_prep.ipynb
        - notebooks/006_data_understanding.ipynb
        - notebooks/007_modeling_and_evaluation.ipynb
        - notebooks/008_advanced_scikitlearn.ipynb
        - notebooks/009_decision_trees.ipynb
        - notebooks/010_random_forests.ipynb
        - notebooks/011_gradient_boosting.ipynb

    # Overall DataLab overview page
    - datalab/index.qmd

    # Iteration
    - part: datalab/iteration-1/index.qmd
      chapters:
        - datalab/iteration-1/i1_t1_nb1_classification.ipynb
        - datalab/iteration-1/i1_t1_nb2_regression.ipynb
        - datalab/iteration-1/i1_t1_nb3_clustering.ipynb

    # Iteration 2
    - part: datalab/iteration-2/index.qmd
      chapters:
        - datalab/iteration-2/i2_t3_nb1_understanding_hopv_stability_csv.ipynb
        - datalab/iteration-2/i2_t3_nb2_understanding_hopv_homolumo_data.ipynb
        - datalab/iteration-2/i2_t4_nb1_data_prep.ipynb
        - datalab/iteration-2/i2_t5_nb1_classification.ipynb
        - datalab/iteration-2/i2_t6_nb1_regression.ipynb
        - datalab/iteration-2/i2_t7_nb1_clustering.ipynb
  
    # Iteration 3
    - part: datalab/iteration-3/index.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true
    number-depth: 2